version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
    - 5432:5432

  backend:
    image: darkdace/foodgram-project:latest
    restart: always
    volumes:
     - static_value:/app/static/
     - media_value:/app/media/
     - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      - frontend

volumes:
  data:
  static_value:
  media_value:
  redoc:
